export const expertsPageContent = {
  homeKicker: "Meet the Experts",
  homeTitle: "Senior technology experts for consequential decisions.",
  homeText: "Work directly with trusted advisors who combine architecture, delivery leadership and business judgment.",
  homeButton: "View all experts",
  pageKicker: "Experts",
  pageTitle: "Senior judgment, directly involved.",
  pageText: "A small core team supported by a trusted network of specialists. No junior staffing model and no distance between the client and technical leadership.",
  cardCta: "View Profile",
  profileHeroKicker: "Trusted technology advisor",
  consultationButton: "Book Consultation",
  linkedinButton: "LinkedIn",
  sections: {
    executiveSummary: "Executive Summary",
    quote: "Perspective",
    expertise: "Expertise",
    expertiseTitle: "Where this expert creates value.",
    industries: "Industries",
    languages: "Languages",
    engagements: "Typical Engagements",
    certifications: "Certifications & Courses",
    certificationsTitle: "Certifications and Courses.",
    technologies: "Technology Focus",
    technologiesTitle: "Platforms, systems and technical domains.",
  },
};
