export const languages = ["en", "ua"] as const;
export type Language = (typeof languages)[number];

export const pages = [
  "services",
  "case-studies",
  "about",
  "experts",
  "certifications",
  "insights",
  "contact",
  "privacy",
  "imprint",
] as const;
export type PageSlug = (typeof pages)[number];

export const languageNames: Record<Language, string> = { en: "EN", ua: "UA" };

const certifications = {
  cloud: [
    "AWS Certified Solutions Architect – Professional",
    "AWS Certified Solutions Architect – Associate",
    "AWS Certified Cloud Practitioner",
    "Google Kubernetes Engine",
  ],
  salesforce: [
    "Salesforce Certified System Architect",
    "Salesforce Certified Application Architect",
  ],
  enterprise: [
    "Oracle Database Administrator Certified Professional",
    "Ericsson Certified Associate – CBiO",
  ],
  data: [
    "Managerial Data Analytics for Digital Transformation",
    "Introduction to Big Data",
    "R Programming",
    "Reproducible Research",
  ],
  business: [
    "Digital Transformation and Platforms",
    "Digital Age Product Design and Development",
    "Leadership Effectiveness",
    "Firm Level Economics",
  ],
};

const vladyslavCertifications = [
  "Elements of AI - University of Helsinki",
  "Gen AI and Agentic AI for Software Engineering - SET University",
];

const content = {
  en: {
    nav: ["Services", "Expertise", "About", "Experts", "Certifications", "Insights"],
    consult: "Schedule a consultation",
    email: "Send an email",
    explore: "Explore services",
    accessibility: {
      home: "LyoPro home",
      navigation: "Main navigation",
      language: "Choose language",
      menu: "Toggle navigation",
    },
    metadata: {
      homeTitle: "Senior Engineering & Technology Consulting",
      description: "Senior engineers and CTO-level architects solving complex software, cloud and enterprise technology challenges.",
      servicesDescription: "CTO-level technology consulting, solution architecture, Salesforce, cloud, DevOps, data and custom software engineering.",
      pageTitles: {
        services: "Engineering Services",
        "case-studies": "Expertise",
        about: "About",
        experts: "Experts",
        certifications: "Certifications",
        insights: "Insights",
        contact: "Contact",
        privacy: "Privacy Policy",
        imprint: "Legal Notice",
      },
    },
    footer: {
      statement: "Senior engineers and CTO-level architects helping companies design, build and modernize complex software systems.",
      expertise: "Expertise",
      company: "Company",
      connect: "Connect",
      services: "Services",
      cases: "Expertise",
      certifications: "Certifications",
      about: "About",
      experts: "Experts",
      insights: "Insights",
      contact: "Contact",
      email: "Email",
      region: "Europe · International",
      privacy: "Privacy",
      imprint: "Imprint",
    },
    finalCta: {
      kicker: "Start with a conversation",
      consult: "Schedule a consultation",
      email: "Send an email",
    },
    home: {
      eyebrow: "Senior engineering · Europe & International",
      headline: "Engineering complex software for companies that can’t afford mistakes.",
      intro: "A compact team of senior engineers, solution architects and CTO-level specialists designing, building and modernizing reliable digital systems.",
      trust: "30+ years of engineering experience · CTO-level leadership · Enterprise-grade architecture",
      visual: {
        labels: ["BUSINESS", "CLOUD", "DATA", "SYSTEMS"],
        statusLabel: "Architecture status",
        status: "Systems aligned",
        aria: "Abstract software architecture diagram",
      },
      metricsIntro: {
        kicker: "Built for consequential work",
        text: "Technical depth where reliability, scale and long-term decisions matter.",
      },
      metrics: [
        ["30+", "Years of experience among key engineers"],
        ["CTO", "Level technical leadership"],
        ["Senior", "Experts, not a junior outsourcing model"],
        ["Global", "Multilingual work across Europe and beyond"],
      ],
      problemsKicker: "Where we create value",
      problemsTitle: "Complex technical problems, resolved before they become expensive business problems.",
      problems: [
        ["Legacy modernization", "Replace fragile systems without disrupting the business they support."],
        ["Internal systems", "Turn complex operations into clear, dependable digital workflows."],
        ["Architecture & scale", "Remove bottlenecks and design for the next stage of growth."],
        ["Salesforce ecosystems", "Make CRM architecture fit real business processes and integrations."],
        ["Cloud infrastructure", "Build observable, secure infrastructure with disciplined operating costs."],
        ["Project recovery", "Establish technical clarity and regain control of failing initiatives."],
      ],
      servicesKicker: "Capabilities",
      servicesTitle: "Senior expertise across the full technology lifecycle.",
      services: [
        { id: "01", title: "Technology Consulting", summary: "Turn business goals into a clear technical strategy, investment plan and delivery roadmap.", items: ["Technical strategy", "System audits", "Technical due diligence"] },
        { id: "02", title: "Solution Architecture", summary: "Design secure, scalable systems and integrations before expensive implementation begins.", items: ["Enterprise architecture", "Cloud-native design", "Integration planning"] },
        { id: "03", title: "Custom Software", summary: "Build mission-critical internal platforms, workflows and backend systems around your operation.", items: ["Internal systems", "Business platforms", "Workflow automation"] },
        { id: "04", title: "Salesforce Solutions", summary: "Architect, integrate and optimize Salesforce for complex enterprise operations.", items: ["System architecture", "Enterprise integrations", "Process automation"] },
        { id: "05", title: "Cloud & DevOps", summary: "Modernize infrastructure for reliable delivery, observability and controlled scale.", items: ["AWS architecture", "Cloud migration", "CI/CD & Kubernetes"] },
        { id: "06", title: "Data, AI & Automation", summary: "Make operational data useful and automate processes where the business case is clear.", items: ["Data pipelines", "Applied AI", "Business intelligence"] },
      ],
      whyKicker: "The LyoPro standard",
      whyTitle: "Not another outsourcing vendor. A senior technical partner.",
      whyIntro: "We connect architecture, delivery and business reality in one senior team.",
      whyLink: "How we think",
      principles: [
        ["01", "CTO-level thinking", "Every technical decision is evaluated against business goals, operating risk and long-term cost."],
        ["02", "Architecture before code", "We define structure, constraints and tradeoffs before implementation creates momentum in the wrong direction."],
        ["03", "Senior-only expertise", "Clients work directly with the people who understand and make the consequential decisions."],
        ["04", "Technical clarity", "We make complex systems understandable, risks visible and next steps defensible."],
        ["05", "Serious without bureaucracy", "Enterprise-grade discipline with the speed and accountability of a compact team."],
      ],
      experts: {
        kicker: "Senior experts",
        title: "Experience you can put in the room.",
        leadRole: "Lead Solution Architect",
        leadSkills: "Enterprise systems · AWS · Integrations",
        salesforceRole: "Salesforce System Architect",
        salesforceSkills: "CRM ecosystems · Automation · Data",
        noteKicker: "Compact by design",
        note: "Deep expertise. Direct access. No layers of account management.",
        link: "Meet the experts",
      },
      casesKicker: "Selected work",
      casesTitle: "Proven thinking across complex technical projects.",
      caseLink: "View case study",
      processKicker: "How we work",
      processTitle: "A disciplined path from ambiguity to reliable delivery.",
      process: [
        ["Discovery", "Understand the goals, context, risks and constraints."],
        ["Architecture", "Define structure, data flows, integrations and infrastructure."],
        ["Implementation", "Build with senior engineering practices and visible progress."],
        ["Validation", "Test reliability, security, performance and business fit."],
        ["Delivery", "Deploy, document and support the system after launch."],
      ],
      finalTitle: "Have a complex technical challenge?",
      finalText: "Talk directly with senior engineers who can evaluate the options, risks and next steps.",
    },
    pages: {
      services: {
        kicker: "Engineering services",
        title: "Expert engineering for complex digital systems.",
        text: "From early technical strategy to architecture, development, cloud, Salesforce and automation — we build systems that remain reliable as the business evolves.",
        problemsLabel: "Typical client problems",
        problems: ["Unclear technical direction", "High operating or maintenance cost", "Systems that no longer support the business", "Risky dependencies and limited visibility"],
        deliverablesLabel: "What we deliver",
        extraDeliverables: ["Implementation roadmap", "Technical documentation"],
        ctaTitle: "Need clarity before committing to a build?",
        ctaText: "Start with a direct technical conversation about the system, constraints and viable paths forward.",
      },
      cases: {
        kicker: "Expertise",
        title: "Selected systems. Clear engineering outcomes.",
        text: "Four case studies across public-sector data, enterprise reporting, automated telephony and telecom transformation.",
        ctaTitle: "Your project may be the next case worth discussing.",
        ctaText: "Tell us where the current system is limiting the business.",
      },
      about: {
        kicker: "About LyoPro",
        title: "Built by engineers who have solved complex problems for decades.",
        text: "We are a compact team of senior engineers, CTOs and technology consultants. Our strength is not size — it is depth of experience.",
        quote: "“The best technical decision is the one that remains sound when the business, team and system have all changed.”",
        paragraphs: [
          "We built LyoPro around a simple premise: companies facing consequential technology decisions need direct access to experienced people.",
          "That means understanding the operation before proposing software, architecture before implementation, and explicit tradeoffs instead of fashionable defaults.",
        ],
        values: [
          ["01", "Senior by design", "The people in the room are the people doing the thinking."],
          ["02", "Business-focused", "Technology serves an operating model, customer need or measurable outcome."],
          ["03", "International", "Clear collaboration across cultures and European markets."],
          ["04", "Independent judgment", "Recommendations are based on fit, not vendor incentives."],
        ],
        ctaTitle: "Work with a team that values technical clarity.",
        ctaText: "Bring us the challenge, the constraints and the uncomfortable questions.",
      },
      experts: {
        kicker: "Experts",
        title: "Senior judgment, directly involved.",
        text: "A small core team supported by a trusted network of specialists. No junior staffing model and no distance between the client and technical leadership.",
        profiles: [
          ["CTO", "Lead Solution Architect", "30+ years", "Enterprise architecture, AWS, software modernization"],
          ["SA", "Salesforce System Architect", "Senior expert", "Salesforce ecosystems, integrations, process automation"],
          ["DE", "Data & Platform Engineer", "Senior expert", "Data platforms, analytics, cloud-native systems"],
        ],
        tags: ["English", "Europe", "CTO-level"],
        ctaTitle: "Talk to the people who will shape the solution.",
        ctaText: "The first conversation is technical, focused and without a sales layer.",
      },
      certifications: {
        kicker: "Credentials",
        title: "Certified expertise, backed by applied experience.",
        text: "A credibility stack spanning enterprise architecture, cloud, Salesforce, data, business leadership and international communication.",
        groups: [
          ["Cloud", certifications.cloud],
          ["Salesforce", certifications.salesforce],
          ["Databases & Enterprise", certifications.enterprise],
          ["Data & Analytics", certifications.data],
          ["Business & Transformation", certifications.business],
          ["Vladyslav Shmygelskyy", vladyslavCertifications],
          ["Languages", ["English", "Ukrainian"]],
        ],
        ctaTitle: "Credentials matter. Applied judgment matters more.",
        ctaText: "Discuss your architecture with people who have both.",
      },
      insights: {
        kicker: "Insights",
        title: "Clear thinking on consequential technology decisions.",
        text: "Practical perspectives on architecture, modernization, technical leadership and the systems behind durable businesses.",
        read: "read",
        request: "Request article",
        posts: [
          ["Architecture", "How to know when technical debt has become a business constraint", "8 min"],
          ["Leadership", "What a useful architecture review should actually deliver", "6 min"],
          ["Salesforce", "The integration decisions that determine CRM maintainability", "7 min"],
          ["Cloud", "Cloud cost control starts in the architecture, not the invoice", "5 min"],
        ],
        ctaTitle: "Prefer a direct answer to a specific problem?",
        ctaText: "Send us the context. We will tell you whether and how we can help.",
      },
      contact: {
        kicker: "Start a conversation",
        title: "Tell us about the technical challenge.",
        text: "You will speak directly with a senior engineer. Share enough context for us to understand the system, the constraint and what a good outcome looks like.",
        regionLabel: "Region",
        region: "Europe · International",
        languagesLabel: "Languages",
        languages: "English · Ukrainian",
        note: "Your project information is treated as confidential. An NDA can be signed before detailed technical discussions.",
        form: {
          name: "Name", namePlaceholder: "Your name", company: "Company", companyPlaceholder: "Company name",
          email: "Email", phone: "Phone / messenger", projectType: "Project type", selectArea: "Select an area",
          projectOptions: ["Technology consulting", "Solution architecture", "Salesforce", "Custom software development", "Cloud / DevOps", "AI / Data", "Internal system", "Not sure yet"],
          budget: "Budget range", selectBudget: "Select a range", budgetOptions: ["Under €20k", "€20k–€50k", "€50k–€100k", "€100k+", "Not sure yet"],
          message: "What would you like to solve?", messagePlaceholder: "Briefly describe the business context, current system and desired outcome.",
          submit: "Request consultation", sending: "Preparing…", response: "We usually respond within one business day.",
          success: "Your email app has been opened. Send the prepared message to complete your request.",
          error: "Something went wrong. Please email hello@lyopro.com.",
          emailSubject: "Consultation request from",
          emailFields: ["Name", "Company", "Email", "Phone / messenger", "Project type", "Budget"],
        },
      },
      legal: {
        kicker: "Legal",
        privacyTitle: "Privacy Policy",
        imprintTitle: "Legal Notice",
        heroText: "Transparent information about how this website operates.",
        privacyHeading: "Data handling",
        imprintHeading: "Company information",
        placeholder: "This page is prepared as a production-ready placeholder. Replace it with jurisdiction-specific legal company details before launch.",
        contactHeading: "Contact",
        contactText: "For privacy or legal questions, contact hello@lyopro.com.",
        enquiriesHeading: "Website enquiries",
        enquiriesText: "Information submitted through the consultation form is used only to respond to the enquiry and assess a potential engagement.",
      },
    },
  },
  ua: {
    nav: ["Послуги", "Експертиза", "Про нас", "Експерти", "Сертифікації", "Матеріали"],
    consult: "Запланувати консультацію",
    email: "Написати нам",
    explore: "Переглянути послуги",
    accessibility: {
      home: "Головна LyoPro",
      navigation: "Головна навігація",
      language: "Обрати мову",
      menu: "Відкрити або закрити меню",
    },
    metadata: {
      homeTitle: "Senior-інженерія та технологічний консалтинг",
      description: "Senior-інженери та архітектори CTO-рівня вирішують складні завдання у сфері програмного забезпечення, хмарних та корпоративних систем.",
      servicesDescription: "Технологічний консалтинг CTO-рівня, архітектура рішень, Salesforce, хмари, DevOps, дані та розробка спеціалізованого ПЗ.",
      pageTitles: {
        services: "Інженерні послуги",
        "case-studies": "Експертиза",
        about: "Про нас",
        experts: "Експерти",
        certifications: "Сертифікації",
        insights: "Матеріали",
        contact: "Контакти",
        privacy: "Політика конфіденційності",
        imprint: "Юридична інформація",
      },
    },
    footer: {
      statement: "Senior-інженери та архітектори CTO-рівня допомагають компаніям проєктувати, створювати й модернізувати складні програмні системи.",
      expertise: "Експертиза",
      company: "Компанія",
      connect: "Зв’язок",
      services: "Послуги",
      cases: "Експертиза",
      certifications: "Сертифікації",
      about: "Про нас",
      experts: "Експерти",
      insights: "Матеріали",
      contact: "Контакти",
      email: "Електронна пошта",
      region: "Європа · Міжнародні проєкти",
      privacy: "Конфіденційність",
      imprint: "Юридична інформація",
    },
    finalCta: {
      kicker: "Почнімо з розмови",
      consult: "Запланувати консультацію",
      email: "Написати нам",
    },
    home: {
      eyebrow: "Senior-інженерія · Європа та міжнародні проєкти",
      headline: "Створюємо складні програмні системи для компаній, які не можуть дозволити собі помилки.",
      intro: "Компактна команда senior-інженерів, архітекторів рішень і фахівців CTO-рівня проєктує, створює та модернізує надійні цифрові системи.",
      trust: "30+ років інженерного досвіду · CTO-рівень · Корпоративна архітектура",
      visual: {
        labels: ["БІЗНЕС", "ХМАРА", "ДАНІ", "СИСТЕМИ"],
        statusLabel: "Стан архітектури",
        status: "Системи узгоджено",
        aria: "Абстрактна схема програмної архітектури",
      },
      metricsIntro: {
        kicker: "Для відповідальних завдань",
        text: "Технічна глибина там, де важливі надійність, масштаб і довгострокові рішення.",
      },
      metrics: [
        ["30+", "Років досвіду ключових інженерів"],
        ["CTO", "Рівень технічного лідерства"],
        ["Senior", "Експерти замість моделі з junior-фахівцями"],
        ["Global", "Багатомовна робота в Європі та за її межами"],
      ],
      problemsKicker: "Де ми створюємо цінність",
      problemsTitle: "Вирішуємо складні технічні проблеми до того, як вони стануть дорогими бізнес-проблемами.",
      problems: [
        ["Модернізація legacy-систем", "Замінюємо крихкі системи без зупинки бізнес-процесів, які від них залежать."],
        ["Внутрішні системи", "Перетворюємо складні операції на зрозумілі та надійні цифрові процеси."],
        ["Архітектура та масштабування", "Усуваємо вузькі місця й проєктуємо систему для наступного етапу зростання."],
        ["Екосистеми Salesforce", "Адаптуємо CRM-архітектуру до реальних бізнес-процесів та інтеграцій."],
        ["Хмарна інфраструктура", "Створюємо спостережувану й захищену інфраструктуру з контрольованими витратами."],
        ["Відновлення проєктів", "Повертаємо технічну ясність і контроль над проблемними ініціативами."],
      ],
      servicesKicker: "Компетенції",
      servicesTitle: "Senior-експертиза на всіх етапах технологічного циклу.",
      services: [
        { id: "01", title: "Технологічний консалтинг", summary: "Перетворюємо бізнес-цілі на чітку технічну стратегію, інвестиційний план і дорожню карту.", items: ["Технічна стратегія", "Аудит систем", "Технічний due diligence"] },
        { id: "02", title: "Архітектура рішень", summary: "Проєктуємо захищені масштабовані системи й інтеграції до початку дорогої реалізації.", items: ["Корпоративна архітектура", "Cloud-native дизайн", "Планування інтеграцій"] },
        { id: "03", title: "Спеціалізоване ПЗ", summary: "Створюємо критично важливі внутрішні платформи, процеси та backend-системи.", items: ["Внутрішні системи", "Бізнес-платформи", "Автоматизація процесів"] },
        { id: "04", title: "Рішення Salesforce", summary: "Проєктуємо, інтегруємо й оптимізуємо Salesforce для складних корпоративних операцій.", items: ["Архітектура систем", "Корпоративні інтеграції", "Автоматизація процесів"] },
        { id: "05", title: "Хмари та DevOps", summary: "Модернізуємо інфраструктуру для надійного постачання, спостережуваності й контрольованого масштабу.", items: ["Архітектура AWS", "Хмарна міграція", "CI/CD та Kubernetes"] },
        { id: "06", title: "Дані, AI та автоматизація", summary: "Перетворюємо операційні дані на користь і автоматизуємо процеси з чітким бізнес-обґрунтуванням.", items: ["Конвеєри даних", "Прикладний AI", "Бізнес-аналітика"] },
      ],
      whyKicker: "Стандарт LyoPro",
      whyTitle: "Не черговий аутсорсинг. Senior-технічний партнер.",
      whyIntro: "Поєднуємо архітектуру, реалізацію та бізнес-реальність в одній senior-команді.",
      whyLink: "Наш підхід",
      principles: [
        ["01", "Мислення CTO-рівня", "Кожне технічне рішення оцінюємо через бізнес-цілі, операційні ризики та довгострокову вартість."],
        ["02", "Архітектура до коду", "Визначаємо структуру, обмеження й компроміси до того, як реалізація набере неправильного напрямку."],
        ["03", "Лише senior-експертиза", "Клієнти працюють безпосередньо з людьми, які розуміють і ухвалюють ключові рішення."],
        ["04", "Технічна ясність", "Робимо складні системи зрозумілими, ризики — видимими, а наступні кроки — обґрунтованими."],
        ["05", "Серйозність без бюрократії", "Корпоративна дисципліна зі швидкістю та відповідальністю компактної команди."],
      ],
      experts: {
        kicker: "Senior-експерти",
        title: "Досвід, який працює безпосередньо з вами.",
        leadRole: "Провідний архітектор рішень",
        leadSkills: "Корпоративні системи · AWS · Інтеграції",
        salesforceRole: "Системний архітектор Salesforce",
        salesforceSkills: "CRM-екосистеми · Автоматизація · Дані",
        noteKicker: "Компактні за задумом",
        note: "Глибока експертиза. Прямий доступ. Без шарів акаунт-менеджменту.",
        link: "Познайомитися з експертами",
      },
      casesKicker: "Вибрані проєкти",
      casesTitle: "Перевірений досвід у складних технічних проєктах.",
      caseLink: "Переглянути кейс",
      processKicker: "Як ми працюємо",
      processTitle: "Дисциплінований шлях від невизначеності до надійного результату.",
      process: [
        ["Дослідження", "Вивчаємо цілі, контекст, ризики та обмеження."],
        ["Архітектура", "Визначаємо структуру, потоки даних, інтеграції та інфраструктуру."],
        ["Реалізація", "Створюємо рішення за senior-інженерними практиками з прозорим прогресом."],
        ["Перевірка", "Тестуємо надійність, безпеку, продуктивність і відповідність бізнесу."],
        ["Впровадження", "Розгортаємо, документуємо та підтримуємо систему після запуску."],
      ],
      finalTitle: "Маєте складний технічний виклик?",
      finalText: "Обговоріть варіанти, ризики та наступні кроки безпосередньо із senior-інженерами.",
    },
    pages: {
      services: {
        kicker: "Інженерні послуги",
        title: "Експертна інженерія для складних цифрових систем.",
        text: "Від початкової технічної стратегії до архітектури, розробки, хмар, Salesforce та автоматизації — створюємо системи, надійні в міру розвитку бізнесу.",
        problemsLabel: "Типові проблеми клієнтів",
        problems: ["Нечіткий технічний напрямок", "Висока вартість експлуатації або підтримки", "Системи більше не відповідають потребам бізнесу", "Ризикові залежності та недостатня прозорість"],
        deliverablesLabel: "Що ви отримуєте",
        extraDeliverables: ["Дорожня карта реалізації", "Технічна документація"],
        ctaTitle: "Потрібна ясність до початку розробки?",
        ctaText: "Почніть із прямої технічної розмови про систему, обмеження та реалістичні шляхи вперед.",
      },
      cases: {
        kicker: "Експертиза",
        title: "Вибрані системи. Чіткі інженерні результати.",
        text: "Чотири кейси з даних державного сектору, корпоративної звітності, автоматизованої телефонії та телеком-трансформації.",
        ctaTitle: "Ваш проєкт може стати наступним кейсом для обговорення.",
        ctaText: "Розкажіть, де поточна система обмежує бізнес.",
      },
      about: {
        kicker: "Про LyoPro",
        title: "Створено інженерами, які десятиліттями вирішують складні завдання.",
        text: "Ми — компактна команда senior-інженерів, CTO та технологічних консультантів. Наша сила не в розмірі, а в глибині досвіду.",
        quote: "«Найкраще технічне рішення залишається обґрунтованим, навіть коли бізнес, команда й система вже змінилися».",
        paragraphs: [
          "Ми побудували LyoPro на простій засаді: компаніям, які ухвалюють відповідальні технологічні рішення, потрібен прямий доступ до досвідчених фахівців.",
          "Це означає спочатку зрозуміти операції, потім пропонувати ПЗ; спочатку архітектура, потім реалізація; чіткі компроміси замість модних стандартних рішень.",
        ],
        values: [
          ["01", "Senior-команда за задумом", "У розмові беруть участь ті самі люди, які виконують інженерну роботу."],
          ["02", "Фокус на бізнесі", "Технологія має підтримувати операційну модель, потребу клієнта або вимірюваний результат."],
          ["03", "Міжнародний підхід", "Зрозуміла співпраця між культурами та європейськими ринками."],
          ["04", "Незалежне судження", "Рекомендації ґрунтуються на відповідності завданню, а не на інтересах постачальників."],
        ],
        ctaTitle: "Працюйте з командою, яка цінує технічну ясність.",
        ctaText: "Принесіть нам виклик, обмеження та незручні запитання.",
      },
      experts: {
        kicker: "Експерти",
        title: "Senior-рішення з прямою участю.",
        text: "Невелика основна команда, яку підтримує перевірена мережа фахівців. Без junior-моделі та дистанції між клієнтом і технічним керівництвом.",
        profiles: [
          ["CTO", "Провідний архітектор рішень", "30+ років", "Корпоративна архітектура, AWS, модернізація ПЗ"],
          ["SA", "Системний архітектор Salesforce", "Senior-експерт", "Екосистеми Salesforce, інтеграції, автоматизація процесів"],
          ["DE", "Інженер даних і платформ", "Senior-експерт", "Платформи даних, аналітика, cloud-native системи"],
        ],
        tags: ["Англійська", "Європа", "CTO-рівень"],
        ctaTitle: "Поговоріть із людьми, які формуватимуть рішення.",
        ctaText: "Перша розмова — технічна, сфокусована та без посередників із продажу.",
      },
      certifications: {
        kicker: "Кваліфікації",
        title: "Сертифікована експертиза, підтверджена практикою.",
        text: "Компетенції у корпоративній архітектурі, хмарах, Salesforce, даних, бізнес-лідерстві та міжнародній комунікації.",
        groups: [
          ["Хмарні технології", certifications.cloud],
          ["Salesforce", certifications.salesforce],
          ["Бази даних і корпоративні системи", certifications.enterprise],
          ["Дані та аналітика", certifications.data],
          ["Бізнес і трансформація", certifications.business],
          ["Vladyslav Shmygelskyy", vladyslavCertifications],
          ["Мови", ["Англійська", "Українська"]],
        ],
        ctaTitle: "Сертифікації важливі. Практичне судження — ще важливіше.",
        ctaText: "Обговоріть архітектуру з людьми, які мають і те, й інше.",
      },
      insights: {
        kicker: "Матеріали",
        title: "Чітке мислення для відповідальних технологічних рішень.",
        text: "Практичні погляди на архітектуру, модернізацію, технічне лідерство та системи, що підтримують стійкий бізнес.",
        read: "читання",
        request: "Запросити матеріал",
        posts: [
          ["Архітектура", "Як зрозуміти, що технічний борг став обмеженням для бізнесу", "8 хв"],
          ["Лідерство", "Що насправді має дати корисний архітектурний аудит", "6 хв"],
          ["Salesforce", "Інтеграційні рішення, що визначають підтримуваність CRM", "7 хв"],
          ["Хмари", "Контроль хмарних витрат починається з архітектури, а не з рахунку", "5 хв"],
        ],
        ctaTitle: "Потрібна пряма відповідь на конкретну проблему?",
        ctaText: "Надішліть контекст. Ми чесно скажемо, чи можемо допомогти і як саме.",
      },
      contact: {
        kicker: "Почнімо розмову",
        title: "Розкажіть про технічний виклик.",
        text: "Ви говоритимете безпосередньо із senior-інженером. Опишіть контекст, систему, обмеження та бажаний результат.",
        regionLabel: "Регіон",
        region: "Європа · Міжнародні проєкти",
        languagesLabel: "Мови",
        languages: "Англійська · Українська",
        note: "Інформація про ваш проєкт залишається конфіденційною. До детального технічного обговорення можемо підписати NDA.",
        form: {
          name: "Ім’я", namePlaceholder: "Ваше ім’я", company: "Компанія", companyPlaceholder: "Назва компанії",
          email: "Електронна пошта", phone: "Телефон / месенджер", projectType: "Тип проєкту", selectArea: "Оберіть напрям",
          projectOptions: ["Технологічний консалтинг", "Архітектура рішень", "Salesforce", "Спеціалізована розробка ПЗ", "Хмари / DevOps", "AI / Дані", "Внутрішня система", "Поки не впевнений"],
          budget: "Бюджет", selectBudget: "Оберіть діапазон", budgetOptions: ["До €20 тис.", "€20–50 тис.", "€50–100 тис.", "€100 тис.+", "Поки не визначено"],
          message: "Яке завдання потрібно вирішити?", messagePlaceholder: "Коротко опишіть бізнес-контекст, поточну систему та бажаний результат.",
          submit: "Запросити консультацію", sending: "Підготовка…", response: "Зазвичай відповідаємо протягом одного робочого дня.",
          success: "Поштову програму відкрито. Надішліть підготовлений лист, щоб завершити звернення.",
          error: "Сталася помилка. Напишіть на hello@lyopro.com.",
          emailSubject: "Запит на консультацію від",
          emailFields: ["Ім’я", "Компанія", "Електронна пошта", "Телефон / месенджер", "Тип проєкту", "Бюджет"],
        },
      },
      legal: {
        kicker: "Юридична інформація",
        privacyTitle: "Політика конфіденційності",
        imprintTitle: "Юридична інформація",
        heroText: "Прозора інформація про роботу цього вебсайту.",
        privacyHeading: "Обробка даних",
        imprintHeading: "Інформація про компанію",
        placeholder: "Ця сторінка є підготовленим шаблоном. Перед запуском її потрібно замінити юридичними даними відповідно до юрисдикції компанії.",
        contactHeading: "Контакти",
        contactText: "З питань конфіденційності або юридичних питань пишіть на hello@lyopro.com.",
        enquiriesHeading: "Звернення через сайт",
        enquiriesText: "Інформація з форми консультації використовується лише для відповіді на звернення та оцінки потенційної співпраці.",
      },
    },
  },
} as const;

export function getLocale(lang: Language) {
  return content[lang];
}
